"use client"

import { FormEvent, useState } from "react"
import { LogOut, Pencil, Plus, Save, Trash2 } from "lucide-react"
import { useProducts } from "@/components/product-store"
import type { Product } from "@/lib/products"

const blankProduct: Product = { id: "", name: "", type: "Fine Jewelry", slug: "", priceInr: 0, image: "", gallery: [], tags: [], category: "Fine Jewelry", goldPurity: "18K Gold", certificate: "", origin: "Jaipur, India", description: "", isFeatured: false, view: true, carat: "", metal: "" }
const fields: Array<[keyof Product, string]> = [["name", "Product Name"], ["priceInr", "Price (INR)"], ["category", "Category"], ["carat", "Carat"], ["goldPurity", "Gold Purity"], ["certificate", "Certificate"], ["origin", "Origin"], ["image", "Main Image URL"], ["gallery", "Additional Image URLs (comma separated)"], ["description", "Description"]]

export default function AdminPage() {
  const { products, saveProduct, deleteProduct } = useProducts()
  const [authenticated, setAuthenticated] = useState(false)
  const [password, setPassword] = useState("")
  const [editing, setEditing] = useState<Product | null>(null)
  const login = (event: FormEvent) => { event.preventDefault(); if (password === "clp2026") { setAuthenticated(true); setPassword("") } else alert("Incorrect password") }
  if (!authenticated) return <main className="admin-page"><section className="admin-login"><p className="eyebrow">Private workspace</p><h1>CLP Admin</h1><p>Sign in to manage the collection.</p><form onSubmit={login}><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoFocus required /></label><button className="admin-button" type="submit">Enter dashboard</button></form></section></main>
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; const product = { ...editing, id: editing.id || editing.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""), slug: editing.slug || editing.id || editing.name.toLowerCase().replace(/[^a-z0-9]+/g, "-"), priceInr: Number(editing.priceInr), gallery: Array.isArray(editing.gallery) ? editing.gallery : String(editing.gallery).split(",").map((item) => item.trim()).filter(Boolean), tags: editing.tags || [] }; saveProduct(product); setEditing(null) }
  return <main className="admin-page"><header className="admin-header"><div><p className="eyebrow">Private workspace</p><h1>CLP Admin</h1></div><button className="admin-logout" onClick={() => { setAuthenticated(false); window.location.href = "/" }}><LogOut size={15} /> Log out</button></header><section className="admin-stats"><div><span>Total products</span><strong>{products.length}</strong></div><div><span>Featured</span><strong>{products.filter((product) => product.isFeatured).length}</strong></div><div><span>Categories</span><strong>{new Set(products.map((product) => product.category)).size}</strong></div></section><div className="admin-toolbar"><h2>Products</h2><button className="admin-button" onClick={() => setEditing({ ...blankProduct })}><Plus size={16} /> Add product</button></div><div className="admin-table">{products.map((product) => <article key={product.id}><div><strong>{product.name}</strong><span>{product.category} · ₹{product.priceInr.toLocaleString("en-IN")}</span></div><div className="admin-actions"><button onClick={() => setEditing({ ...product })} aria-label={`Edit ${product.name}`}><Pencil size={15} /></button><button onClick={() => window.confirm(`Delete ${product.name}?`) && deleteProduct(product.id)} aria-label={`Delete ${product.name}`}><Trash2 size={15} /></button></div></article>)}</div>{editing && <div className="admin-editor-backdrop"><form className="admin-editor" onSubmit={submit}><div className="admin-editor-heading"><div><p className="eyebrow">Collection editor</p><h2>{editing.id ? "Edit product" : "Add product"}</h2></div><button type="button" onClick={() => setEditing(null)} aria-label="Close editor">×</button></div><div className="admin-form-grid">{fields.map(([key, label]) => <label key={key}>{label}{key === "description" ? <textarea rows={4} value={Array.isArray(editing[key]) ? editing[key].join(", ") : String(editing[key] ?? "")} onChange={(event) => setEditing({ ...editing, [key]: event.target.value })} required={String(key) === "name"} /> : key === "category" ? <select value={String(editing[key])} onChange={(event) => setEditing({ ...editing, category: event.target.value as Product["category"] })}><option>Emerald</option><option>Gold</option><option>Ruby</option><option>Loose Gemstones</option><option>Fine Jewelry</option></select> : <input type={key === "priceInr" ? "number" : "text"} value={Array.isArray(editing[key]) ? editing[key].join(", ") : String(editing[key] ?? "")} onChange={(event) => setEditing({ ...editing, [key]: key === "priceInr" ? Number(event.target.value) : event.target.value })} required={String(key) === "name"} />}</label>)}</div><label className="admin-check"><input type="checkbox" checked={editing.isFeatured} onChange={(event) => setEditing({ ...editing, isFeatured: event.target.checked })} /> Featured product</label><button className="admin-button" type="submit"><Save size={16} /> Save product</button></form></div>}</main>
}
