"use client"

import { useEffect, useMemo, useState } from "react"
import { Search } from "lucide-react"
import { createClient } from "@/lib/supabase/client"
import { getLocalOrders, type LocalOrder } from "@/lib/order-store"

type Order = LocalOrder & { customer_email?: string }
export function OrdersDashboard() {
  const [orders, setOrders] = useState<Order[]>([]); const [status, setStatus] = useState("All"); const [destination, setDestination] = useState("All"); const [query, setQuery] = useState(""); const [error, setError] = useState("")
  useEffect(() => { const sync = () => setOrders((current) => [...getLocalOrders(), ...current.filter((order) => !getLocalOrders().some((local) => local.id === order.id))]); sync(); const onCreated = () => sync(); window.addEventListener("clp:order-created", onCreated); createClient().from("orders").select("*").order("created_at", { ascending: false }).then(({ data, error: queryError }) => { if (queryError && queryError.code !== "42P01") setError(queryError.message); else setOrders((current) => [...getLocalOrders(), ...((data || []) as Order[]).filter((order) => !getLocalOrders().some((local) => local.id === order.id)), ...current.filter((order) => !getLocalOrders().some((local) => local.id === order.id) && !((data || []) as Order[]).some((remote) => remote.id === order.id))]) }); return () => window.removeEventListener("clp:order-created", onCreated) }, [])
  const filtered = useMemo(() => orders.filter((order) => (status === "All" || order.dispatch_status === status) && (destination === "All" || order.destination === destination) && `${order.customer_name} ${order.customer_email} ${order.product_name}`.toLowerCase().includes(query.toLowerCase())), [orders, status, destination, query])
  return <section className="orders-dashboard"><div className="orders-toolbar"><div><p className="eyebrow">Etsy-style shop manager</p><h2>Orders</h2></div><label className="orders-search"><Search size={16} /><input placeholder="Search orders" value={query} onChange={(event) => setQuery(event.target.value)} /></label></div><div className="orders-filters"><select value={status} onChange={(event) => setStatus(event.target.value)}><option>All</option><option>New</option><option>Completed</option><option>Overdue</option></select><select value={destination} onChange={(event) => setDestination(event.target.value)}><option>All</option><option>India</option><option>International</option></select></div>{error && <p className="admin-muted">{error}</p>}<div className="orders-list">{filtered.map((order) => <article className="order-card" key={order.id}><div className="order-card-top"><div><span className={`order-status order-${order.dispatch_status.toLowerCase()}`}>{order.dispatch_status}</span><h3>{order.product_name}</h3><p>{order.customer_name} · {order.customer_email}</p></div><strong>₹{Number(order.total_inr).toLocaleString("en-IN")}</strong></div><div className="order-address"><strong>Ship to</strong><span>{order.address}, {order.city}, {order.state} — {order.pincode}</span></div>{order.buyer_notes && <p className="order-note"><strong>Buyer note:</strong> {order.buyer_notes}</p>}</article>)}</div>{!error && !filtered.length && <p className="admin-muted">No orders match these filters.</p>}</section>
}
